server:
  port: 8080

spring:
  application:
    name: boot-demo-db-redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.185:3306/activity?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
  redis:
    host: 192.168.0.132
    port: 6379
    database: 3
    password: kxyx92108
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spatome.boot.dao

redisson:
  address: redis://192.168.0.132:6379
  password: kxyx92108
  database: 3