server:
  port: 8080

spring:
  rabbitmq:
    host: 192.168.0.185
    port: 5672
    virtual-host: cloud
    username: spatome
    password: spatome
    publisher-confirms: true
    publisher-returns: true