server:
  port: 9099
  session:
    timeout: 7200

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.132:3306/dhy?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: kxyx92108
#  redis:
#    host: 192.168.0.132 
#    port: 6379
#    database: 1
#    password: kxyx92108
#    timeout: 15000
  rabbitmq:
    host: 192.168.0.185
    port: 5672
    virtual-host: cloud
    username: spatome
    password: spatome
    publisher-confirms: true
    publisher-returns: true

mybatis:
  mapper-locations: classpath:mapper/message/*.xml
  type-aliases-package: com.shby.message.entity

pagehelper:
  helper-dialect: mysql
  reasonable: false
  offsetAsPageNum: true

my:
  